# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Secret Variables
BP_CRED_CRED_CALM_PASSWORD = read_local_file("BP_CRED_CRED_CALM_PASSWORD")
BP_CRED_CRED_PC_PASSWORD = read_local_file("BP_CRED_CRED_PC_PASSWORD")


# Credentials
BP_CRED_CRED_CALM = basic_cred(
    "admin",
    BP_CRED_CRED_CALM_PASSWORD,
    name="CRED_CALM",
    type="PASSWORD",
)
BP_CRED_CRED_PC = basic_cred(
    "admin",
    BP_CRED_CRED_PC_PASSWORD,
    name="CRED_PC",
    type="PASSWORD",
)

# Runbook
@runbook
def STEE_Runbook_20250108(credentials=[BP_CRED_CRED_CALM, BP_CRED_CRED_PC]):

    """Sample code provided by STEE on 8 Jan 25"""

    CalmVM_IP = CalmVariable.Simple(
        "10.42.155.60",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )  # noqa
    account_name = CalmVariable.WithOptions.FromTask(
        CalmVarTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts",
                "_Runbook_STEE_Runbook_20250108_variable_account_name_Task_SampleTask.py",
            ),
        ),
        label="Please select the account name",
        is_mandatory=True,
        is_hidden=False,
        description="",
        value="NTNX_LOCAL_AZ_ITC",
    )  # noqa
    PC_IP = CalmVariable.WithOptions.FromTask(
        CalmVarTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts",
                "_Runbook_STEE_Runbook_20250108_variable_PC_IP_Task_SampleTask.py",
            ),
        ),
        label="Please select the Prism Central IP",
        is_mandatory=True,
        is_hidden=False,
        description="",
        value="10.42.155.39",
    )  # noqa
    tenant_uuid = CalmVariable.Simple(
        "Tenant1",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )  # noqa

    CalmTask.Exec.escript.py3(
        name="Task 1",
        filename=os.path.join(
            "scripts", "_Runbook_STEE_Runbook_20250108_Task_Task1.py"
        ),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("BP Design Project")
