print ("-------------------------")
print ("")
print ("Nexus Registry Host Name:")
print ("@@{Nexus_vmname}@@")
print ("")
print ("Nexus Registry IP Address:")
print ("@@{Nexus.address}@@")
print ("")
print ("Nexus Registry URLs:")
print ("View Repositories:")
print ("https://@@{Nexus_vmname}@@.@@{domain_name}@@/repository/test-group/")
print ("")
print ("")
print ("")
print ("-------------------------")