# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Secret Variables
BP_CRED_CRED_PC_PASSWORD = read_local_file("BP_CRED_CRED_PC_PASSWORD")
BP_CRED_CRED_CALM_PASSWORD = read_local_file("BP_CRED_CRED_CALM_PASSWORD")


# Credentials
BP_CRED_CRED_PC = basic_cred(
    "admin",
    BP_CRED_CRED_PC_PASSWORD,
    name="CRED_PC",
    type="PASSWORD",
)
BP_CRED_CRED_CALM = basic_cred(
    "admin",
    BP_CRED_CRED_CALM_PASSWORD,
    name="CRED_CALM",
    type="PASSWORD",
)

# Runbook
@runbook
def List_VM_Metric_v4(credentials=[BP_CRED_CRED_PC, BP_CRED_CRED_CALM]):

    CalmVM_IP = CalmVariable.Simple(
        "10.42.155.60",
        label="",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    account_name = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts",
                "_Runbook_List_VM_Metric_v4_variable_account_name_Task_SampleTask.py",
            ),
        ),
        label="Please select the account name",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    PC_IP = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts",
                "_Runbook_List_VM_Metric_v4_variable_PC_IP_Task_SampleTask.py",
            ),
        ),
        label="Please select the Prism Central IP",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    vm = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts", "_Runbook_List_VM_Metric_v4_variable_vm_Task_SampleTask.py"
            ),
        ),
        label="Please select the VM",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    startTime = CalmVariable.Simple(
        "2025-01-03T15%3A30%3A00.000%2B08%3A00",
        label="Please key in the start time",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="3 Jan 2025 15:30 pm on GMT+8.  The value need to be encoded to comply with HTTP requirement for special character.",
    )  # noqa
    endTime = CalmVariable.Simple(
        "2025-01-03T15%3A35%3A00.000%2B08%3A00",
        label="Please key in the end time",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="3 Jan 2025 15:35 pm on GMT+8.  The value need to be encoded to comply with HTTP requirement for special character.",
    )  # noqa
    statType = CalmVariable.WithOptions(
        ["AVG", "MIN", "MAX", "LAST", "SUM", "COUNT", "$UNKNOWN"],
        label="Please select the stat type",
        default="AVG",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    queryParam = CalmVariable.WithOptions(
        ["stats", "extId", "links", "tenantId"],
        label="Please select the query parameters",
        default="stats",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    CalmTask.Exec.escript.py3(
        name="GetVMStat",
        filename=os.path.join(
            "scripts", "_Runbook_List_VM_Metric_v4_Task_GetVMStat.py"
        ),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("BP Design Project")
