print "-------------------------"
print ""
print "Developer Workstaion Host Name:"
print "@@{name}@@"
print ""
print "Developer Workstaion IP Address:"
print "@@{address}@@"
print ""
print "-------------------------"