print "-------------------------"
print ""
print "Jenkins Master Host Name:"
print "@@{Jenkins Master.name}@@"
print ""
print "Jenkins Master IP Address:"
print "@@{Jenkins Master.address}@@"
print ""
print "Initial Authorization Password:"
print "@@{Jenkins Master.jenkins_authorization}@@"
print ""
print "Jenkins Master URL:"
print "http://@@{Jenkins Master.address}@@:8080/"
print ""
print "-------------------------"