# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Secret Variables
BP_CRED_CRED_CALM_PASSWORD = read_local_file("BP_CRED_CRED_CALM_PASSWORD")
BP_CRED_CRED_PC_PASSWORD = read_local_file("BP_CRED_CRED_PC_PASSWORD")


# Credentials
BP_CRED_CRED_CALM = basic_cred(
    "admin",
    BP_CRED_CRED_CALM_PASSWORD,
    name="CRED_CALM",
    type="PASSWORD",
)
BP_CRED_CRED_PC = basic_cred(
    "admin",
    BP_CRED_CRED_PC_PASSWORD,
    name="CRED_PC",
    type="PASSWORD",
)

# Runbook
@runbook
def LIST_PBR(credentials=[BP_CRED_CRED_CALM, BP_CRED_CRED_PC]):

    TENANT_TAG = CalmVariable.Simple(
        "Tenant1",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    minimum_priority = CalmVariable.Simple(
        "1", label="", is_mandatory=False, is_hidden=True, runtime=False, description=""
    )  # noqa
    CalmTask.SetVariable.escript.py3(
        name="Get Nutanix Variables",
        filename=os.path.join(
            "scripts", "_Runbook_LIST_PBR_Task_GetNutanixVariables.py"
        ),
        variables=[
            "ip_calm",
            "username_calm",
            "password_calm",
            "ip_pc",
            "username_pc",
            "password_pc",
        ],
    )

    CalmTask.SetVariable.escript.py3(
        name="Get Tenant Tag",
        filename=os.path.join("scripts", "_Runbook_LIST_PBR_Task_GetTenantTag.py"),
        variables=["tenant_tag"],
    )

    CalmTask.Exec.escript.py3(
        name="List Policies",
        filename=os.path.join("scripts", "_Runbook_LIST_PBR_Task_ListPolicies.py"),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("Tenant1")
