# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Secret Variables
BP_CRED_CRED_PC_PASSWORD = read_local_file("BP_CRED_CRED_PC_PASSWORD")
BP_CRED_CRED_CALM_PASSWORD = read_local_file("BP_CRED_CRED_CALM_PASSWORD")


# Credentials
BP_CRED_CRED_PC = basic_cred(
    "admin",
    BP_CRED_CRED_PC_PASSWORD,
    name="CRED_PC",
    type="PASSWORD",
)
BP_CRED_CRED_CALM = basic_cred(
    "admin",
    BP_CRED_CRED_CALM_PASSWORD,
    name="CRED_CALM",
    type="PASSWORD",
)

# Runbook
@runbook
def List_PBR_v4(credentials=[BP_CRED_CRED_PC, BP_CRED_CRED_CALM]):

    """Use v4 api"""

    CalmVM_IP = CalmVariable.Simple(
        "10.55.88.50",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=False,
        description="",
    )  # noqa
    account_name = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts",
                "_Runbook_List_PBR_v4_variable_account_name_Task_SampleTask.py",
            ),
        ),
        label="Please select the account name",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    PC_IP = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts", "_Runbook_List_PBR_v4_variable_PC_IP_Task_SampleTask.py"
            ),
        ),
        label="Please select the Prism Central IP",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    vpc = CalmVariable.WithOptions.FromTask(
        CalmTask.Exec.escript.py3(
            name="",
            filename=os.path.join(
                "scripts", "_Runbook_List_PBR_v4_variable_vpc_Task_SampleTask.py"
            ),
        ),
        label="Please select the VPC",
        is_mandatory=True,
        is_hidden=False,
        description="",
    )  # noqa
    TENANT_TAG = CalmVariable.Simple(
        "Tenant1",
        label="",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    minimum_priority = CalmVariable.Simple(
        "1", label="", is_mandatory=True, is_hidden=False, runtime=True, description=""
    )  # noqa
    CalmTask.SetVariable.escript.py3(
        name="Get Nutanix Variables",
        filename=os.path.join(
            "scripts", "_Runbook_List_PBR_v4_Task_GetNutanixVariables.py"
        ),
        variables=[
            "ip_calm",
            "username_calm",
            "password_calm",
            "ip_pc",
            "username_pc",
            "password_pc",
        ],
    )

    CalmTask.SetVariable.escript.py3(
        name="Get Tenant Tag",
        filename=os.path.join("scripts", "_Runbook_List_PBR_v4_Task_GetTenantTag.py"),
        variables=["tenant_tag"],
    )

    CalmTask.Exec.escript.py3(
        name="List Policies",
        filename=os.path.join("scripts", "_Runbook_List_PBR_v4_Task_ListPolicies.py"),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("BP Design Project")
