# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata


# Secret Variables
_Runbook_LIST_TENANT_ENTITIES_Py3_variable_input_credentials = read_local_file(
    "_Runbook_LIST_TENANT_ENTITIES_Py3_variable_input_credentials"
)
BP_CRED_CRED_PC_PASSWORD = read_local_file("BP_CRED_CRED_PC_PASSWORD")
BP_CRED_CRED_CALM_PASSWORD = read_local_file("BP_CRED_CRED_CALM_PASSWORD")


# Credentials
BP_CRED_CRED_PC = basic_cred(
    "admin",
    BP_CRED_CRED_PC_PASSWORD,
    name="CRED_PC",
    type="PASSWORD",
)
BP_CRED_CRED_CALM = basic_cred(
    "admin",
    BP_CRED_CRED_CALM_PASSWORD,
    name="CRED_CALM",
    type="PASSWORD",
)

# Runbook
@runbook
def LIST_TENANT_ENTITIES_Py3(credentials=[BP_CRED_CRED_PC, BP_CRED_CRED_CALM]):

    """Lists all Tenant entities (either VMs or Subnets)"""

    TENANT_TAG = CalmVariable.Simple(
        "Tenant1",
        label="",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    ENTITY_TYPE = CalmVariable.WithOptions(
        ["VM", "Subnet"],
        label="",
        default="Subnet",
        is_mandatory=True,
        is_hidden=False,
        runtime=True,
        description="",
    )  # noqa
    input_credentials = CalmVariable.Simple.Secret(
        _Runbook_LIST_TENANT_ENTITIES_Py3_variable_input_credentials,
        label="Credentials (only used for proxy launches)",
        is_mandatory=False,
        is_hidden=False,
        runtime=True,
        description='{"ip_calm": "", "username_calm": "", "password_calm": "", "ip_pc": "", "username_pc": "", "password_pc": ""}',
    )  # noqa
    CalmTask.SetVariable.escript.py3(
        name="Get Dynamic Variables",
        filename=os.path.join(
            "scripts", "_Runbook_LIST_TENANT_ENTITIES_Py3_Task_GetDynamicVariables.py"
        ),
        variables=[
            "ip_calm",
            "username_calm",
            "password_calm",
            "ip_pc",
            "username_pc",
            "password_pc",
        ],
    )

    CalmTask.SetVariable.escript.py3(
        name="Get Tenant Tag",
        filename=os.path.join(
            "scripts", "_Runbook_LIST_TENANT_ENTITIES_Py3_Task_GetTenantTag.py"
        ),
        variables=["tenant_tag"],
    )

    CalmTask.Exec.escript.py3(
        name="List Tenant Entities",
        filename=os.path.join(
            "scripts", "_Runbook_LIST_TENANT_ENTITIES_Py3_Task_ListTenantEntities.py"
        ),
    )


class RunbookMetadata(Metadata):
    project = Ref.Project("Tenant1")
